// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v6.30.2
// source: pkg/proto/scraper.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Сообщение запроса с URL для скрейпинга
type FetchRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchRequest) Reset() {
	*x = FetchRequest{}
	mi := &file_pkg_proto_scraper_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchRequest) ProtoMessage() {}

func (x *FetchRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scraper_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchRequest.ProtoReflect.Descriptor instead.
func (*FetchRequest) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scraper_proto_rawDescGZIP(), []int{0}
}

func (x *FetchRequest) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

// Сообщение ответа с результатами скрейпинга
type FetchResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          string                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FetchResponse) Reset() {
	*x = FetchResponse{}
	mi := &file_pkg_proto_scraper_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FetchResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FetchResponse) ProtoMessage() {}

func (x *FetchResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_proto_scraper_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FetchResponse.ProtoReflect.Descriptor instead.
func (*FetchResponse) Descriptor() ([]byte, []int) {
	return file_pkg_proto_scraper_proto_rawDescGZIP(), []int{1}
}

func (x *FetchResponse) GetData() string {
	if x != nil {
		return x.Data
	}
	return ""
}

var File_pkg_proto_scraper_proto protoreflect.FileDescriptor

const file_pkg_proto_scraper_proto_rawDesc = "" +
	"\n" +
	"\x17pkg/proto/scraper.proto\x12\x05proto\" \n" +
	"\fFetchRequest\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"#\n" +
	"\rFetchResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\tR\x04data2H\n" +
	"\x0eScraperService\x126\n" +
	"\tFetchData\x12\x13.proto.FetchRequest\x1a\x14.proto.FetchResponseB\vZ\tpkg/protob\x06proto3"

var (
	file_pkg_proto_scraper_proto_rawDescOnce sync.Once
	file_pkg_proto_scraper_proto_rawDescData []byte
)

func file_pkg_proto_scraper_proto_rawDescGZIP() []byte {
	file_pkg_proto_scraper_proto_rawDescOnce.Do(func() {
		file_pkg_proto_scraper_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_proto_scraper_proto_rawDesc), len(file_pkg_proto_scraper_proto_rawDesc)))
	})
	return file_pkg_proto_scraper_proto_rawDescData
}

var file_pkg_proto_scraper_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_pkg_proto_scraper_proto_goTypes = []any{
	(*FetchRequest)(nil),  // 0: proto.FetchRequest
	(*FetchResponse)(nil), // 1: proto.FetchResponse
}
var file_pkg_proto_scraper_proto_depIdxs = []int32{
	0, // 0: proto.ScraperService.FetchData:input_type -> proto.FetchRequest
	1, // 1: proto.ScraperService.FetchData:output_type -> proto.FetchResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pkg_proto_scraper_proto_init() }
func file_pkg_proto_scraper_proto_init() {
	if File_pkg_proto_scraper_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_proto_scraper_proto_rawDesc), len(file_pkg_proto_scraper_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_proto_scraper_proto_goTypes,
		DependencyIndexes: file_pkg_proto_scraper_proto_depIdxs,
		MessageInfos:      file_pkg_proto_scraper_proto_msgTypes,
	}.Build()
	File_pkg_proto_scraper_proto = out.File
	file_pkg_proto_scraper_proto_goTypes = nil
	file_pkg_proto_scraper_proto_depIdxs = nil
}
