# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scraping.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'scraping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escraping.proto\x12\x08scraping\x1a\x0c\x63ommon.proto\"D\n\rScrapeRequest\x12\r\n\x05\x65ntry\x18\x01 \x01(\t\x12$\n\x05rules\x18\x02 \x01(\x0b\x32\x15.scraping.ScrapeRules\"5\n\x0eScrapeResponse\x12#\n\tdocuments\x18\x01 \x03(\x0b\x32\x10.common.Document\"\x85\x01\n\x0bScrapeRules\x12\x11\n\tmax_depth\x18\x01 \x01(\r\x12\x11\n\tmax_pages\x18\x02 \x01(\r\x12\'\n\x0fscrape_patterns\x18\x03 \x03(\x0b\x32\x0e.scraping.Rule\x12\'\n\x0e\x66orbidden_urls\x18\x04 \x03(\x0b\x32\x0f.scraping.Regex\":\n\x04Rule\x12\x1c\n\x03url\x18\x01 \x01(\x0b\x32\x0f.scraping.Regex\x12\x14\n\x0c\x63ss_selector\x18\x02 \x01(\t\"\x18\n\x05Regex\x12\x0f\n\x07pattern\x18\x01 \x01(\t2P\n\x0fScrapingService\x12=\n\x06Scrape\x12\x17.scraping.ScrapeRequest\x1a\x18.scraping.ScrapeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scraping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPEREQUEST']._serialized_start=42
  _globals['_SCRAPEREQUEST']._serialized_end=110
  _globals['_SCRAPERESPONSE']._serialized_start=112
  _globals['_SCRAPERESPONSE']._serialized_end=165
  _globals['_SCRAPERULES']._serialized_start=168
  _globals['_SCRAPERULES']._serialized_end=301
  _globals['_RULE']._serialized_start=303
  _globals['_RULE']._serialized_end=361
  _globals['_REGEX']._serialized_start=363
  _globals['_REGEX']._serialized_end=387
  _globals['_SCRAPINGSERVICE']._serialized_start=389
  _globals['_SCRAPINGSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
