import uuid
import logging
import grpc
import os
import time
from datetime import datetime

# Import generated gRPC modules
from controller.rpc import controller_pb2_grpc
from controller.rpc import controller_pb2
from controller.rpc import userdb_pb2
from controller.rpc import userdb_pb2_grpc
from controller.rpc import vectordb_pb2
from controller.rpc import vectordb_pb2_grpc
from controller.rpc import scraping_pb2
from controller.rpc import scraping_pb2_grpc
from controller.rpc import llms_pb2
from controller.rpc import llms_pb2_grpc
from controller.rpc import logging_pb2
from controller.rpc import logging_pb2_grpc
from controller.rpc import common_pb2

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('controller')


class ControllerServicer(controller_pb2_grpc.ControllerServicer):
    """Implementation of the Controller service."""

    def __init__(self, config=None):
        self.config = config or {}
        
        # Initialize service connections
        self.userdb_channel = grpc.insecure_channel(
            self.config.get('USERDB_SERVICE', 'localhost:50051')
        )
        self.userdb_stub = userdb_pb2_grpc.DatabaseServiceStub(self.userdb_channel)
        
        self.vectordb_channel = grpc.insecure_channel(
            self.config.get('VECTORDB_SERVICE', 'localhost:50052')
        )
        self.vectordb_stub = vectordb_pb2_grpc.VectorDatabaseServiceStub(self.vectordb_channel)
        
        self.scraping_channel = grpc.insecure_channel(
            self.config.get('SCRAPING_SERVICE', 'localhost:50053')
        )
        self.scraping_stub = scraping_pb2_grpc.ScrapingServiceStub(self.scraping_channel)
        
        self.llm_channel = grpc.insecure_channel(
            self.config.get('LLM_SERVICE', 'localhost:50054')
        )
        self.llm_stub = llms_pb2_grpc.LLMServiceStub(self.llm_channel)

        self.logging_channel = None
        self.logging_stub = None
        if self.config.get('LOGGING_SERVICE'):
            self.logging_channel = grpc.insecure_channel(
                self.config.get('LOGGING_SERVICE')
            )
            self.logging_stub = logging_pb2_grpc.LoggingServiceStub(self.logging_channel)

    def log_event(self, message, level=logging_pb2.INFO):
        """Log event using the logging service if available, otherwise use local logging."""
        logger.info(message)
        
        if self.logging_stub:
            try:
                timestamp = datetime.now().timestamp()
                event = logging_pb2.LogEvent(
                    source='controller',
                    message=message,
                    timestamp=timestamp,
                    level=level
                )
                self.logging_stub.LogEvent(logging_pb2.LogEventRequest(events=[event]))
            except Exception as e:
                logger.error(f"Failed to log to logging service: {e}")

    def CreatePipeline(self, request, context):
        """
        Implements CreatePipeline method:
        1. Save user info to database
        2. Generate a random token for authorization
        3. Scrape documents using URL and rules
        4. Insert documents into vector database
        5. Return generated token
        """
        start_time = time.time()
        request_id = str(uuid.uuid4())
        self.log_event(f"Request {request_id}: CreatePipeline started for entry URL: {request.entry_docs_url}")

        try:
            # Step 1: Create user in database
            user = userdb_pb2.User(
                token="",  # Token will be generated by the service
                language=request.language,
                llm_preference="",  # Default LLM preference
                description=request.description,
                num_requests=0
            )
            user_request = userdb_pb2.CreateUserRequest(user=user)
            
            try:
                user_response = self.userdb_stub.CreateUser(user_request)
                token = user_response.token
                self.log_event(f"Request {request_id}: User created with token: {token[:5]}...")
            except grpc.RpcError as e:
                error_msg = f"Failed to create user: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 2: Scrape documents
            scrape_request = scraping_pb2.ScrapeRequest(
                entry=request.entry_docs_url,
                rules=request.rules
            )
            
            try:
                self.log_event(f"Request {request_id}: Scraping started for URL: {request.entry_docs_url}")
                scrape_response = self.scraping_stub.Scrape(scrape_request)
                documents = scrape_response.documents
                self.log_event(f"Request {request_id}: Scraping completed, {len(documents)} documents retrieved")
            except grpc.RpcError as e:
                error_msg = f"Failed to scrape documents: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 3: Create collection in vector database
            # Use the token as the collection name for easy retrieval
            collection_name = token
            
            # Get embedding model for the specified language
            try:
                models_request = vectordb_pb2.GetEmbeddingModelsRequest(language=request.language)
                models_response = self.vectordb_stub.GetEmbeddingModels(models_request)
                
                if not models_response.models:
                    error_msg = f"No embedding models available for language: {request.language}"
                    self.log_event(error_msg, logging_pb2.ERROR)
                    context.set_code(grpc.StatusCode.NOT_FOUND)
                    context.set_details(error_msg)
                    return controller_pb2.CreatePipelineResponse()
                
                embedding_model = models_response.models[0].name
            except grpc.RpcError as e:
                error_msg = f"Failed to get embedding models: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()
            
            # Create collection and add documents
            create_collection_request = vectordb_pb2.CreateCollectionRequest(
                collection_name=collection_name,
                embedding_model=embedding_model,
                documents=documents
            )
            
            try:
                self.log_event(f"Request {request_id}: Creating collection in vector database with {len(documents)} documents")
                self.vectordb_stub.CreateCollection(create_collection_request)
                self.log_event(f"Request {request_id}: Collection created successfully")
            except grpc.RpcError as e:
                error_msg = f"Failed to create collection: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 4: Return generated token
            elapsed_time = time.time() - start_time
            self.log_event(f"Request {request_id}: CreatePipeline completed in {elapsed_time:.2f} seconds")
            return controller_pb2.CreatePipelineResponse(token=token)
            
        except Exception as e:
            error_msg = f"Unexpected error in CreatePipeline: {str(e)}"
            self.log_event(error_msg, logging_pb2.ERROR)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(error_msg)
            return controller_pb2.CreatePipelineResponse()

    def AnswerPrompt(self, request, context):
        """
        Implements AnswerPrompt method:
        1. Authenticate user using token
        2. Retrieve relevant documents from vector database
        3. Send prompt and documents to LLM service
        4. Return generated answer
        """
        start_time = time.time()
        request_id = str(uuid.uuid4())
        token_prefix = request.token[:5] if len(request.token) >= 5 else request.token
        self.log_event(f"Request {request_id}: AnswerPrompt started for token: {token_prefix}...")

        try:
            # Step 1: Validate user token
            user_request = userdb_pb2.GetUserRequest(token=request.token)
            
            try:
                self.log_event(f"Request {request_id}: Validating user token")
                user_response = self.userdb_stub.GetUser(user_request)
                user = user_response.user
                self.log_event(f"Request {request_id}: User validated successfully")
            except grpc.RpcError as e:
                if e.code() == grpc.StatusCode.NOT_FOUND:
                    error_msg = f"Invalid token: {token_prefix}..."
                    self.log_event(error_msg, logging_pb2.WARNING)
                    context.set_code(grpc.StatusCode.UNAUTHENTICATED)
                    context.set_details("Invalid token")
                    return controller_pb2.AnswerPromptResponse()
                else:
                    error_msg = f"Failed to validate user: {e.details() if hasattr(e, 'details') else str(e)}"
                    self.log_event(error_msg, logging_pb2.ERROR)
                    context.set_code(grpc.StatusCode.INTERNAL)
                    context.set_details(error_msg)
                    return controller_pb2.AnswerPromptResponse()

            # Step 2: Update request count
            try:
                count_request = userdb_pb2.UpdateUserRequestCountRequest(token=request.token, delta=1)
                self.userdb_stub.UpdateUserRequestCount(count_request)
                self.log_event(f"Request {request_id}: User request count updated")
            except grpc.RpcError as e:
                # Non-critical error, log but continue
                error_msg = f"Failed to update request count: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.WARNING)

            # Step 3: Search for relevant documents
            collection_name = request.token  # Using token as collection name
            search_request = vectordb_pb2.SearchRequest(
                collection_name=collection_name,
                query=request.prompt,
                limit=5  # Return top 5 most relevant documents
            )
            
            try:
                self.log_event(f"Request {request_id}: Searching for relevant documents")
                search_response = self.vectordb_stub.Search(search_request)
                relevant_documents = search_response.results
                self.log_event(f"Request {request_id}: Found {len(relevant_documents)} relevant documents")
            except grpc.RpcError as e:
                error_msg = f"Failed to search documents: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()

            # Step 4: Generate answer using LLM
            # First, get available models for the user's language
            try:
                models_request = llms_pb2.GetAvailableModelsRequest(language=user.language)
                models_response = self.llm_stub.GetAvailableModels(models_request)
                
                if not models_response.models:
                    error_msg = f"No LLM models available for language: {user.language}"
                    self.log_event(error_msg, logging_pb2.ERROR)
                    context.set_code(grpc.StatusCode.FAILED_PRECONDITION)
                    context.set_details(error_msg)
                    return controller_pb2.AnswerPromptResponse()
                
                # Use user preference if available, otherwise use the first model
                model_name = user.llm_preference if user.llm_preference else models_response.models[0].name
            except grpc.RpcError as e:
                error_msg = f"Failed to get LLM models: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()
            
            # Create context with relevant documents
            context_info = f"User query: {request.prompt}\nLanguage: {user.language}"
            llm_context = llms_pb2.Context(
                info=context_info,
                documents=relevant_documents
            )
            
            # Generate answer
            generate_request = llms_pb2.GenerateAnswerRequest(
                model_name=model_name,
                question=request.prompt,
                context=llm_context
            )
            
            try:
                self.log_event(f"Request {request_id}: Generating answer using LLM model: {model_name}")
                generate_response = self.llm_stub.GenerateAnswer(generate_request)
                answer = generate_response.answer
                self.log_event(f"Request {request_id}: Answer generated successfully")
            except grpc.RpcError as e:
                error_msg = f"Failed to generate answer: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging_pb2.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()

            # Step 5: Return the answer
            elapsed_time = time.time() - start_time
            self.log_event(f"Request {request_id}: AnswerPrompt completed in {elapsed_time:.2f} seconds")
            return controller_pb2.AnswerPromptResponse(answer=answer)
            
        except Exception as e:
            error_msg = f"Unexpected error in AnswerPrompt: {str(e)}"
            self.log_event(error_msg, logging_pb2.ERROR)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(error_msg)
            return controller_pb2.AnswerPromptResponse()
