import uuid
import logging
import grpc
import os
import time
from datetime import datetime

# Import generated gRPC modules
from controller.rpc import controller_pb2_grpc
from controller.rpc import controller_pb2
from controller.rpc import userdb_pb2
from controller.rpc import userdb_pb2_grpc
from controller.rpc import vectordb_pb2
from controller.rpc import vectordb_pb2_grpc
from controller.rpc import scraping_pb2
from controller.rpc import scraping_pb2_grpc
from controller.rpc import llms_pb2
from controller.rpc import llms_pb2_grpc
from controller.rpc import common_pb2

# Import Redis utilities
from controller.redis_utils import redis_manager

# Set up logging
logging.basicConfig(
    level=logging.INFO,
    format='%(asctime)s - %(name)s - %(levelname)s - %(message)s'
)
logger = logging.getLogger('controller')


class ControllerServicer(controller_pb2_grpc.ControllerServicer):
    """Implementation of the Controller service."""

    def __init__(self, config=None):
        self.config = config or {}
        
        # Get timeout values from config
        self.default_timeout = self.config.get('DEFAULT_TIMEOUT', 30)  # 30 seconds default
        self.userdb_timeout = self.config.get('USERDB_TIMEOUT', 15)
        self.vectordb_timeout = self.config.get('VECTORDB_TIMEOUT', 45)
        self.scraping_timeout = self.config.get('SCRAPING_TIMEOUT', 120)
        self.llm_timeout = self.config.get('LLM_TIMEOUT', 60)
        
        # Initialize service connections with updated options
        # Reduce ping frequency to avoid "too_many_pings" error (ENHANCE_YOUR_CALM)
        channel_options = [
            # Increase time between pings from 10s to 60s
            ('grpc.keepalive_time_ms', 60000),  
            # Increase timeout waiting for ping responses to 20s
            ('grpc.keepalive_timeout_ms', 20000),  
            # Only send pings when there are active calls
            ('grpc.keepalive_permit_without_calls', False),  
            # Allow server to send pings without data
            ('grpc.http2.max_pings_without_data', 2),
            # Client will comply with server's ping policy
            ('grpc.client_channel_backup_poll_interval_ms', 200)
        ]
        
        # Initialize service connections
        self.userdb_channel = grpc.insecure_channel(
            self.config.get('USERDB_SERVICE', 'localhost:50051'),
            options=channel_options
        )
        self.userdb_stub = userdb_pb2_grpc.DatabaseServiceStub(self.userdb_channel)
        
        self.vectordb_channel = grpc.insecure_channel(
            self.config.get('VECTORDB_SERVICE', 'localhost:50052'),
            options=channel_options
        )
        self.vectordb_stub = vectordb_pb2_grpc.VectorDatabaseServiceStub(self.vectordb_channel)
        
        self.scraping_channel = grpc.insecure_channel(
            self.config.get('SCRAPING_SERVICE', 'localhost:50053'),
            options=channel_options
        )
        self.scraping_stub = scraping_pb2_grpc.ScrapingServiceStub(self.scraping_channel)
        
        self.llm_channel = grpc.insecure_channel(
            self.config.get('LLM_SERVICE', 'localhost:50054'),
            options=channel_options
        )
        self.llm_stub = llms_pb2_grpc.LLMServiceStub(self.llm_channel)

    def log_event(self, message, level=logging.INFO):
        """Log event using local logging."""
        if level == logging.ERROR:
            logger.error(message)
        elif level == logging.WARNING:
            logger.warning(message)
        else:
            logger.info(message)

    def _convert_common_to_vectordb_document(self, doc):
        """Convert common.Document to vectordb.Document."""
        return vectordb_pb2.Document(
            source=doc.source,
            content=doc.content
        )
    
    def _convert_vectordb_to_common_document(self, doc):
        """Convert vectordb.Document to common.Document."""
        return common_pb2.Document(
            source=doc.source,
            content=doc.content
        )

    def CreatePipeline(self, request, context):
        """
        Implements CreatePipeline method:
        1. Save user info to database
        2. Generate a random token for authorization
        3. Scrape documents using URL and rules
        4. Insert documents into vector database
        5. Return generated token
        """
        start_time = time.time()
        request_id = str(uuid.uuid4())
        self.log_event(f"Request {request_id}: CreatePipeline started for entry URL: {request.entry_docs_url}")

        try:
            # Step 1: Create user in database
            user = userdb_pb2.User(
                token="",  # Token will be generated by the service
                language=request.language,
                llm_preference="",  # Default LLM preference
                description=request.description,
                num_requests=0
            )
            user_request = userdb_pb2.CreateUserRequest(user=user)
            
            try:
                user_response = self.userdb_stub.CreateUser(
                    user_request, 
                    timeout=self.userdb_timeout
                )
                token = user_response.token
                self.log_event(f"Request {request_id}: User created with token: {token[:5]}...")
            except grpc.RpcError as e:
                error_msg = f"Failed to create user: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 2: Scrape documents
            scrape_request = scraping_pb2.ScrapeRequest(
                entry=request.entry_docs_url,
                rules=request.rules
            )
            
            try:
                self.log_event(f"Request {request_id}: Scraping started for URL: {request.entry_docs_url}")
                scrape_response = self.scraping_stub.Scrape(
                    scrape_request,
                    timeout=self.scraping_timeout
                )
                documents = scrape_response.documents
                self.log_event(f"Request {request_id}: Scraping completed, {len(documents)} documents retrieved")
            except grpc.RpcError as e:
                error_msg = f"Failed to scrape documents: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 3: Create collection in vector database
            # Use the token as the collection name for easy retrieval
            collection_name = token
            
            # Get embedding model for the specified language
            try:
                models_request = vectordb_pb2.GetEmbeddingModelsRequest(language=request.language)
                models_response = self.vectordb_stub.GetEmbeddingModels(
                    models_request, 
                    timeout=self.vectordb_timeout
                )
                
                if not models_response.models:
                    error_msg = f"No embedding models available for language: {request.language}"
                    self.log_event(error_msg, logging.ERROR)
                    context.set_code(grpc.StatusCode.NOT_FOUND)
                    context.set_details(error_msg)
                    return controller_pb2.CreatePipelineResponse()
                
                embedding_model = models_response.models[0].name
            except grpc.RpcError as e:
                error_msg = f"Failed to get embedding models: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()
            
            # Convert common.Document to vectordb.Document
            vectordb_documents = [self._convert_common_to_vectordb_document(doc) for doc in documents]
            
            # Create collection and add documents
            create_collection_request = vectordb_pb2.CreateCollectionRequest(
                collection_name=collection_name,
                embedding_model=embedding_model,
                documents=vectordb_documents
            )
            
            try:
                self.log_event(f"Request {request_id}: Creating collection in vector database with {len(documents)} documents")
                self.vectordb_stub.CreateCollection(
                    create_collection_request,
                    timeout=self.vectordb_timeout
                )
                self.log_event(f"Request {request_id}: Collection created successfully")
            except grpc.RpcError as e:
                error_msg = f"Failed to create collection: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.CreatePipelineResponse()

            # Step 4: Return generated token
            elapsed_time = time.time() - start_time
            self.log_event(f"Request {request_id}: CreatePipeline completed in {elapsed_time:.2f} seconds")
            return controller_pb2.CreatePipelineResponse(token=token)
            
        except Exception as e:
            error_msg = f"Unexpected error in CreatePipeline: {str(e)}"
            self.log_event(error_msg, logging.ERROR)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(error_msg)
            return controller_pb2.CreatePipelineResponse()

    def AnswerPrompt(self, request, context):
        """
        Implements AnswerPrompt method:
        1. Authenticate user using token
        2. Retrieve relevant documents from vector database
        3. Send prompt and documents to LLM service
        4. Return generated answer
        """
        start_time = time.time()
        request_id = str(uuid.uuid4())
        token_prefix = request.token[:5] if len(request.token) >= 5 else request.token
        self.log_event(f"Request {request_id}: AnswerPrompt started for token: {token_prefix}...")

        try:
            # Step 1: Validate user token
            user_request = userdb_pb2.GetUserRequest(token=request.token)
            
            try:
                self.log_event(f"Request {request_id}: Validating user token")
                user_response = self.userdb_stub.GetUser(
                    user_request,
                    timeout=self.userdb_timeout
                )
                user = user_response.user
                self.log_event(f"Request {request_id}: User validated successfully")
            except grpc.RpcError as e:
                if e.code() == grpc.StatusCode.NOT_FOUND:
                    error_msg = f"Invalid token: {token_prefix}..."
                    self.log_event(error_msg, logging.WARNING)
                    context.set_code(grpc.StatusCode.UNAUTHENTICATED)
                    context.set_details("Invalid token")
                    return controller_pb2.AnswerPromptResponse()
                else:
                    error_msg = f"Failed to validate user: {e.details() if hasattr(e, 'details') else str(e)}"
                    self.log_event(error_msg, logging.ERROR)
                    context.set_code(grpc.StatusCode.INTERNAL)
                    context.set_details(error_msg)
                    return controller_pb2.AnswerPromptResponse()

            # Step 2: Update request count
            try:
                count_request = userdb_pb2.UpdateUserRequestCountRequest(token=request.token, delta=1)
                self.userdb_stub.UpdateUserRequestCount(
                    count_request,
                    timeout=self.userdb_timeout
                )
                self.log_event(f"Request {request_id}: User request count updated")
            except grpc.RpcError as e:
                # Non-critical error, log but continue
                error_msg = f"Failed to update request count: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.WARNING)

            # Step 3: Search for relevant documents
            collection_name = request.token  # Using token as collection name
            search_request = vectordb_pb2.SearchRequest(
                collection_name=collection_name,
                query=request.prompt,
                limit=5  # Return top 5 most relevant documents
            )
            
            try:
                self.log_event(f"Request {request_id}: Searching for relevant documents")
                search_response = self.vectordb_stub.Search(
                    search_request,
                    timeout=self.vectordb_timeout
                )
                # Convert vectordb.Document to common.Document
                relevant_documents = [self._convert_vectordb_to_common_document(doc) for doc in search_response.results]
                self.log_event(f"Request {request_id}: Found {len(relevant_documents)} relevant documents")
            except grpc.RpcError as e:
                error_msg = f"Failed to search documents: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()

            # Step 4: Generate answer using LLM
            # First, get available models for the user's language
            try:
                models_request = llms_pb2.GetAvailableModelsRequest(language=user.language)
                models_response = self.llm_stub.GetAvailableModels(
                    models_request,
                    timeout=self.llm_timeout
                )
                
                if not models_response.models:
                    error_msg = f"No LLM models available for language: {user.language}"
                    self.log_event(error_msg, logging.ERROR)
                    context.set_code(grpc.StatusCode.FAILED_PRECONDITION)
                    context.set_details(error_msg)
                    return controller_pb2.AnswerPromptResponse()
                
                # Use user preference if available, otherwise use the first model
                model_name = user.llm_preference if user.llm_preference else models_response.models[0].name
            except grpc.RpcError as e:
                error_msg = f"Failed to get LLM models: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()
            
            # Create context with relevant documents
            context_info = None
            llm_context = llms_pb2.Context(
                info=context_info,
                documents=relevant_documents
            )
            
            # Generate answer
            generate_request = llms_pb2.GenerateAnswerRequest(
                model_name=model_name,
                question=request.prompt,
                context=llm_context
            )
            
            try:
                self.log_event(f"Request {request_id}: Generating answer using LLM model: {model_name}")
                generate_response = self.llm_stub.GenerateAnswer(
                    generate_request,
                    timeout=self.llm_timeout
                )
                answer = generate_response.answer
                self.log_event(f"Request {request_id}: Answer generated successfully")
            except grpc.RpcError as e:
                error_msg = f"Failed to generate answer: {e.details() if hasattr(e, 'details') else str(e)}"
                self.log_event(error_msg, logging.ERROR)
                context.set_code(grpc.StatusCode.INTERNAL)
                context.set_details(error_msg)
                return controller_pb2.AnswerPromptResponse()

            # Step 5: Return the answer
            elapsed_time = time.time() - start_time
            self.log_event(f"Request {request_id}: AnswerPrompt completed in {elapsed_time:.2f} seconds")
            return controller_pb2.AnswerPromptResponse(answer=answer)
            
        except Exception as e:
            error_msg = f"Unexpected error in AnswerPrompt: {str(e)}"
            self.log_event(error_msg, logging.ERROR)
            context.set_code(grpc.StatusCode.INTERNAL)
            context.set_details(error_msg)
            return controller_pb2.AnswerPromptResponse()

    def process_pipeline_job(self, job_data):
        """
        Process a pipeline creation job from Redis queue.
        This method contains the same logic as CreatePipeline but adapted for async processing.
        """
        job_id = job_data.get("job_id")
        user_name = job_data.get("user_name")
        description = job_data.get("description")
        language = job_data.get("language")
        entry_docs_url = job_data.get("entry_docs_url")
        rules_data = job_data.get("rules")
        
        self.log_event(f"Processing pipeline job {job_id} for user: {user_name}")
        
        try:
            # Convert rules data back to protobuf format
            scrape_rules_proto = common_pb2.ScrapeRules()
            
            # Fix: Convert string values to integers for max_depth and max_pages
            if rules_data.get("max_depth") is not None:
                try:
                    scrape_rules_proto.max_depth = int(rules_data["max_depth"])
                except (ValueError, TypeError):
                    self.log_event(f"Invalid max_depth value: {rules_data['max_depth']}, using default", logging.WARNING)
                    scrape_rules_proto.max_depth = 3  # Default value
                    
            if rules_data.get("max_pages") is not None:
                try:
                    scrape_rules_proto.max_pages = int(rules_data["max_pages"])
                except (ValueError, TypeError):
                    self.log_event(f"Invalid max_pages value: {rules_data['max_pages']}, using default", logging.WARNING)
                    scrape_rules_proto.max_pages = 100  # Default value

            for rule_data in rules_data.get("scrape_patterns", []):
                rule_proto = scrape_rules_proto.scrape_patterns.add()
                rule_proto.url.pattern = rule_data["url"]["pattern"]
                if rule_data.get("css_selector"):
                    rule_proto.css_selector = rule_data["css_selector"]

            for regex_data in rules_data.get("forbidden_urls", []):
                regex_proto = scrape_rules_proto.forbidden_urls.add()
                regex_proto.pattern = regex_data["pattern"]

            # Step 1: Create user in database
            user = userdb_pb2.User(
                token="",  # Token will be generated by the service
                language=language,
                llm_preference="",  # Default LLM preference
                description=description,
                num_requests=0
            )
            user_request = userdb_pb2.CreateUserRequest(user=user)
            
            user_response = self.userdb_stub.CreateUser(
                user_request, 
                timeout=self.userdb_timeout
            )
            token = user_response.token
            self.log_event(f"Job {job_id}: User created with token: {token[:5]}...")

            # Step 2: Scrape documents
            scrape_request = scraping_pb2.ScrapeRequest(
                entry=entry_docs_url,
                rules=scrape_rules_proto
            )
            
            self.log_event(f"Job {job_id}: Scraping started for URL: {entry_docs_url}")
            scrape_response = self.scraping_stub.Scrape(
                scrape_request,
                timeout=self.scraping_timeout
            )
            documents = scrape_response.documents
            self.log_event(f"Job {job_id}: Scraping completed, {len(documents)} documents retrieved")

            # Step 3: Create collection in vector database
            collection_name = token
            
            # Get embedding model for the specified language
            models_request = vectordb_pb2.GetEmbeddingModelsRequest(language=language)
            models_response = self.vectordb_stub.GetEmbeddingModels(
                models_request, 
                timeout=self.vectordb_timeout
            )
            
            if not models_response.models:
                raise Exception(f"No embedding models available for language: {language}")
            
            embedding_model = models_response.models[0].name
            
            # Convert common.Document to vectordb.Document
            vectordb_documents = [self._convert_common_to_vectordb_document(doc) for doc in documents]
            
            # Create collection and add documents
            create_collection_request = vectordb_pb2.CreateCollectionRequest(
                collection_name=collection_name,
                embedding_model=embedding_model,
                documents=vectordb_documents
            )
            
            self.log_event(f"Job {job_id}: Creating collection in vector database with {len(documents)} documents")
            self.vectordb_stub.CreateCollection(
                create_collection_request,
                timeout=self.vectordb_timeout
            )
            self.log_event(f"Job {job_id}: Collection created successfully")

            # Return the result
            result = {"token": token}
            self.log_event(f"Job {job_id}: Pipeline creation completed successfully")
            return result
            
        except Exception as e:
            error_msg = f"Pipeline creation failed: {str(e)}"
            self.log_event(f"Job {job_id}: {error_msg}", logging.ERROR)
            raise
