# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'common.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0c\x63ommon.proto\x12\x06\x63ommon\"+\n\x08\x44ocument\x12\x0e\n\x06source\x18\x01 \x01(\t\x12\x0f\n\x07\x63ontent\x18\x03 \x01(\t\"\x81\x01\n\x0bScrapeRules\x12\x11\n\tmax_depth\x18\x01 \x01(\r\x12\x11\n\tmax_pages\x18\x02 \x01(\r\x12%\n\x0fscrape_patterns\x18\x03 \x03(\x0b\x32\x0c.common.Rule\x12%\n\x0e\x66orbidden_urls\x18\x04 \x03(\x0b\x32\r.common.Regex\"8\n\x04Rule\x12\x1a\n\x03url\x18\x01 \x01(\x0b\x32\r.common.Regex\x12\x14\n\x0c\x63ss_selector\x18\x02 \x01(\t\"\x18\n\x05Regex\x12\x0f\n\x07pattern\x18\x01 \x01(\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DOCUMENT']._serialized_start=24
  _globals['_DOCUMENT']._serialized_end=67
  _globals['_SCRAPERULES']._serialized_start=70
  _globals['_SCRAPERULES']._serialized_end=199
  _globals['_RULE']._serialized_start=201
  _globals['_RULE']._serialized_end=257
  _globals['_REGEX']._serialized_start=259
  _globals['_REGEX']._serialized_end=283
# @@protoc_insertion_point(module_scope)
