# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: controller.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'controller.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x10\x63ontroller.proto\x12\ncontroller\x1a\x0c\x63ommon.proto\"4\n\x13\x41nswerPromptRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\x0e\n\x06prompt\x18\x02 \x01(\t\"&\n\x14\x41nswerPromptResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"\x8d\x01\n\x15\x43reatePipelineRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x16\n\x0e\x65ntry_docs_url\x18\x04 \x01(\t\x12\"\n\x05rules\x18\x05 \x01(\x0b\x32\x13.common.ScrapeRules\"\'\n\x16\x43reatePipelineResponse\x12\r\n\x05token\x18\x01 \x01(\t2\xbc\x01\n\nController\x12S\n\x0c\x41nswerPrompt\x12\x1f.controller.AnswerPromptRequest\x1a .controller.AnswerPromptResponse\"\x00\x12Y\n\x0e\x43reatePipeline\x12!.controller.CreatePipelineRequest\x1a\".controller.CreatePipelineResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'controller_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ANSWERPROMPTREQUEST']._serialized_start=46
  _globals['_ANSWERPROMPTREQUEST']._serialized_end=98
  _globals['_ANSWERPROMPTRESPONSE']._serialized_start=100
  _globals['_ANSWERPROMPTRESPONSE']._serialized_end=138
  _globals['_CREATEPIPELINEREQUEST']._serialized_start=141
  _globals['_CREATEPIPELINEREQUEST']._serialized_end=282
  _globals['_CREATEPIPELINERESPONSE']._serialized_start=284
  _globals['_CREATEPIPELINERESPONSE']._serialized_end=323
  _globals['_CONTROLLER']._serialized_start=326
  _globals['_CONTROLLER']._serialized_end=514
# @@protoc_insertion_point(module_scope)
