# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: llms.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'llms.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nllms.proto\x12\x04llms\x1a\x0c\x63ommon.proto\"]\n\x15GenerateAnswerRequest\x12\x12\n\nmodel_name\x18\x01 \x01(\t\x12\x10\n\x08question\x18\x02 \x01(\t\x12\x1e\n\x07\x63ontext\x18\x03 \x01(\x0b\x32\r.llms.Context\"(\n\x16GenerateAnswerResponse\x12\x0e\n\x06\x61nswer\x18\x01 \x01(\t\"-\n\x19GetAvailableModelsRequest\x12\x10\n\x08language\x18\x01 \x01(\t\"9\n\x1aGetAvailableModelsResponse\x12\x1b\n\x06models\x18\x01 \x03(\x0b\x32\x0b.llms.Model\"9\n\x05Model\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\x10\n\x08provider\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\"<\n\x07\x43ontext\x12\x0c\n\x04info\x18\x01 \x01(\t\x12#\n\tdocuments\x18\x02 \x03(\x0b\x32\x10.common.Document2\xb2\x01\n\nLLMService\x12K\n\x0eGenerateAnswer\x12\x1b.llms.GenerateAnswerRequest\x1a\x1c.llms.GenerateAnswerResponse\x12W\n\x12GetAvailableModels\x12\x1f.llms.GetAvailableModelsRequest\x1a .llms.GetAvailableModelsResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'llms_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GENERATEANSWERREQUEST']._serialized_start=34
  _globals['_GENERATEANSWERREQUEST']._serialized_end=127
  _globals['_GENERATEANSWERRESPONSE']._serialized_start=129
  _globals['_GENERATEANSWERRESPONSE']._serialized_end=169
  _globals['_GETAVAILABLEMODELSREQUEST']._serialized_start=171
  _globals['_GETAVAILABLEMODELSREQUEST']._serialized_end=216
  _globals['_GETAVAILABLEMODELSRESPONSE']._serialized_start=218
  _globals['_GETAVAILABLEMODELSRESPONSE']._serialized_end=275
  _globals['_MODEL']._serialized_start=277
  _globals['_MODEL']._serialized_end=334
  _globals['_CONTEXT']._serialized_start=336
  _globals['_CONTEXT']._serialized_end=396
  _globals['_LLMSERVICE']._serialized_start=399
  _globals['_LLMSERVICE']._serialized_end=577
# @@protoc_insertion_point(module_scope)
