# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import scraping_pb2 as scraping__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in scraping_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ScrapingServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Scrape = channel.unary_unary(
                '/scraping.ScrapingService/Scrape',
                request_serializer=scraping__pb2.ScrapeRequest.SerializeToString,
                response_deserializer=scraping__pb2.ScrapeResponse.FromString,
                _registered_method=True)


class ScrapingServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Scrape(self, request, context):
        """# Scrape documentation

        Start with `entry` URL

        Recursively visit each page with urls that match at least one of
        regexes provided in `rules.scrape_patterns`. If a match is found,
        extract only the text that is located in the HTML element that matches the `css_selector` 
        provided in the rule. If no `css_selector` is provided, use `main` as the default.

        Do not exceed `rules.max_depth` levels of recursion if `rules.max_depth` is set
        or `rules.max_pages` pages if `rules.max_pages` is set

        Do not visit any page that matches any of the regexes provided in `rules.forbidden_urls`

        Try to split each page into multiple documents using a recursive algorithm
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ScrapingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Scrape': grpc.unary_unary_rpc_method_handler(
                    servicer.Scrape,
                    request_deserializer=scraping__pb2.ScrapeRequest.FromString,
                    response_serializer=scraping__pb2.ScrapeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'scraping.ScrapingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('scraping.ScrapingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ScrapingService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Scrape(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/scraping.ScrapingService/Scrape',
            scraping__pb2.ScrapeRequest.SerializeToString,
            scraping__pb2.ScrapeResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
