# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: scraping.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'scraping.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import common_pb2 as common__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0escraping.proto\x12\x08scraping\x1a\x0c\x63ommon.proto\"B\n\rScrapeRequest\x12\r\n\x05\x65ntry\x18\x01 \x01(\t\x12\"\n\x05rules\x18\x02 \x01(\x0b\x32\x13.common.ScrapeRules\"5\n\x0eScrapeResponse\x12#\n\tdocuments\x18\x01 \x03(\x0b\x32\x10.common.Document2P\n\x0fScrapingService\x12=\n\x06Scrape\x12\x17.scraping.ScrapeRequest\x1a\x18.scraping.ScrapeResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'scraping_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_SCRAPEREQUEST']._serialized_start=42
  _globals['_SCRAPEREQUEST']._serialized_end=108
  _globals['_SCRAPERESPONSE']._serialized_start=110
  _globals['_SCRAPERESPONSE']._serialized_end=163
  _globals['_SCRAPINGSERVICE']._serialized_start=165
  _globals['_SCRAPINGSERVICE']._serialized_end=245
# @@protoc_insertion_point(module_scope)
