# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import userdb_pb2 as userdb__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in userdb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class DatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetUser = channel.unary_unary(
                '/userdb.DatabaseService/GetUser',
                request_serializer=userdb__pb2.GetUserRequest.SerializeToString,
                response_deserializer=userdb__pb2.GetUserResponse.FromString,
                _registered_method=True)
        self.CreateUser = channel.unary_unary(
                '/userdb.DatabaseService/CreateUser',
                request_serializer=userdb__pb2.CreateUserRequest.SerializeToString,
                response_deserializer=userdb__pb2.CreateUserResponse.FromString,
                _registered_method=True)
        self.UpdateUser = channel.unary_unary(
                '/userdb.DatabaseService/UpdateUser',
                request_serializer=userdb__pb2.UpdateUserRequest.SerializeToString,
                response_deserializer=userdb__pb2.UpdateUserResponse.FromString,
                _registered_method=True)
        self.DeleteUser = channel.unary_unary(
                '/userdb.DatabaseService/DeleteUser',
                request_serializer=userdb__pb2.DeleteUserRequest.SerializeToString,
                response_deserializer=userdb__pb2.DeleteUserResponse.FromString,
                _registered_method=True)
        self.UpdateUserRequestCount = channel.unary_unary(
                '/userdb.DatabaseService/UpdateUserRequestCount',
                request_serializer=userdb__pb2.UpdateUserRequestCountRequest.SerializeToString,
                response_deserializer=userdb__pb2.UpdateUserRequestCountResponse.FromString,
                _registered_method=True)


class DatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetUser(self, request, context):
        """Get user by token
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateUser(self, request, context):
        """Create a new user
        Returns the token of the created user
        The user token in the request is ignored
        The token in the request is ignored
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUser(self, request, context):
        """Update an existing user
        The user token in the request is required and must exist in the database
        Only non-null fields in the request will be updated
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteUser(self, request, context):
        """Delete a user by token
        The user token in the request is required and must exist in the database
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateUserRequestCount(self, request, context):
        """Add to the number of requests made by the user
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_DatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUser,
                    request_deserializer=userdb__pb2.GetUserRequest.FromString,
                    response_serializer=userdb__pb2.GetUserResponse.SerializeToString,
            ),
            'CreateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateUser,
                    request_deserializer=userdb__pb2.CreateUserRequest.FromString,
                    response_serializer=userdb__pb2.CreateUserResponse.SerializeToString,
            ),
            'UpdateUser': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUser,
                    request_deserializer=userdb__pb2.UpdateUserRequest.FromString,
                    response_serializer=userdb__pb2.UpdateUserResponse.SerializeToString,
            ),
            'DeleteUser': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteUser,
                    request_deserializer=userdb__pb2.DeleteUserRequest.FromString,
                    response_serializer=userdb__pb2.DeleteUserResponse.SerializeToString,
            ),
            'UpdateUserRequestCount': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateUserRequestCount,
                    request_deserializer=userdb__pb2.UpdateUserRequestCountRequest.FromString,
                    response_serializer=userdb__pb2.UpdateUserRequestCountResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'userdb.DatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('userdb.DatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class DatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userdb.DatabaseService/GetUser',
            userdb__pb2.GetUserRequest.SerializeToString,
            userdb__pb2.GetUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userdb.DatabaseService/CreateUser',
            userdb__pb2.CreateUserRequest.SerializeToString,
            userdb__pb2.CreateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userdb.DatabaseService/UpdateUser',
            userdb__pb2.UpdateUserRequest.SerializeToString,
            userdb__pb2.UpdateUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userdb.DatabaseService/DeleteUser',
            userdb__pb2.DeleteUserRequest.SerializeToString,
            userdb__pb2.DeleteUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateUserRequestCount(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/userdb.DatabaseService/UpdateUserRequestCount',
            userdb__pb2.UpdateUserRequestCountRequest.SerializeToString,
            userdb__pb2.UpdateUserRequestCountResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
