# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: userdb.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'userdb.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cuserdb.proto\x12\x06userdb\"\x1f\n\x0eGetUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"-\n\x0fGetUserResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.userdb.User\"\"\n\x11\x44\x65leteUserRequest\x12\r\n\x05token\x18\x01 \x01(\t\"0\n\x12\x44\x65leteUserResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.userdb.User\"/\n\x11\x43reateUserRequest\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.userdb.User\"#\n\x12\x43reateUserResponse\x12\r\n\x05token\x18\x01 \x01(\t\"/\n\x11UpdateUserRequest\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.userdb.User\"0\n\x12UpdateUserResponse\x12\x1a\n\x04user\x18\x01 \x01(\x0b\x32\x0c.userdb.User\"=\n\x1dUpdateUserRequestCountRequest\x12\r\n\x05token\x18\x01 \x01(\t\x12\r\n\x05\x64\x65lta\x18\x02 \x01(\r\"2\n\x1eUpdateUserRequestCountResponse\x12\x10\n\x08requests\x18\x01 \x01(\x04\"j\n\x04User\x12\r\n\x05token\x18\x02 \x01(\t\x12\x10\n\x08language\x18\x03 \x01(\t\x12\x16\n\x0ellm_preference\x18\x04 \x01(\t\x12\x13\n\x0b\x64\x65scription\x18\x05 \x01(\t\x12\x14\n\x0cnum_requests\x18\x06 \x01(\x05\x32\x8f\x03\n\x0f\x44\x61tabaseService\x12<\n\x07GetUser\x12\x16.userdb.GetUserRequest\x1a\x17.userdb.GetUserResponse\"\x00\x12\x45\n\nCreateUser\x12\x19.userdb.CreateUserRequest\x1a\x1a.userdb.CreateUserResponse\"\x00\x12\x45\n\nUpdateUser\x12\x19.userdb.UpdateUserRequest\x1a\x1a.userdb.UpdateUserResponse\"\x00\x12\x45\n\nDeleteUser\x12\x19.userdb.DeleteUserRequest\x1a\x1a.userdb.DeleteUserResponse\"\x00\x12i\n\x16UpdateUserRequestCount\x12%.userdb.UpdateUserRequestCountRequest\x1a&.userdb.UpdateUserRequestCountResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'userdb_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_GETUSERREQUEST']._serialized_start=24
  _globals['_GETUSERREQUEST']._serialized_end=55
  _globals['_GETUSERRESPONSE']._serialized_start=57
  _globals['_GETUSERRESPONSE']._serialized_end=102
  _globals['_DELETEUSERREQUEST']._serialized_start=104
  _globals['_DELETEUSERREQUEST']._serialized_end=138
  _globals['_DELETEUSERRESPONSE']._serialized_start=140
  _globals['_DELETEUSERRESPONSE']._serialized_end=188
  _globals['_CREATEUSERREQUEST']._serialized_start=190
  _globals['_CREATEUSERREQUEST']._serialized_end=237
  _globals['_CREATEUSERRESPONSE']._serialized_start=239
  _globals['_CREATEUSERRESPONSE']._serialized_end=274
  _globals['_UPDATEUSERREQUEST']._serialized_start=276
  _globals['_UPDATEUSERREQUEST']._serialized_end=323
  _globals['_UPDATEUSERRESPONSE']._serialized_start=325
  _globals['_UPDATEUSERRESPONSE']._serialized_end=373
  _globals['_UPDATEUSERREQUESTCOUNTREQUEST']._serialized_start=375
  _globals['_UPDATEUSERREQUESTCOUNTREQUEST']._serialized_end=436
  _globals['_UPDATEUSERREQUESTCOUNTRESPONSE']._serialized_start=438
  _globals['_UPDATEUSERREQUESTCOUNTRESPONSE']._serialized_end=488
  _globals['_USER']._serialized_start=490
  _globals['_USER']._serialized_end=596
  _globals['_DATABASESERVICE']._serialized_start=599
  _globals['_DATABASESERVICE']._serialized_end=998
# @@protoc_insertion_point(module_scope)
