# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import vectordb_pb2 as vectordb__pb2

GRPC_GENERATED_VERSION = '1.67.1'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in vectordb_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class VectorDatabaseServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateCollection = channel.unary_unary(
                '/vectordb.VectorDatabaseService/CreateCollection',
                request_serializer=vectordb__pb2.CreateCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.CreateCollectionResponse.FromString,
                _registered_method=True)
        self.AddDocuments = channel.unary_unary(
                '/vectordb.VectorDatabaseService/AddDocuments',
                request_serializer=vectordb__pb2.AddDocumentsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.AddDocumentsResponse.FromString,
                _registered_method=True)
        self.Search = channel.unary_unary(
                '/vectordb.VectorDatabaseService/Search',
                request_serializer=vectordb__pb2.SearchRequest.SerializeToString,
                response_deserializer=vectordb__pb2.SearchResponse.FromString,
                _registered_method=True)
        self.DeleteCollection = channel.unary_unary(
                '/vectordb.VectorDatabaseService/DeleteCollection',
                request_serializer=vectordb__pb2.DeleteCollectionRequest.SerializeToString,
                response_deserializer=vectordb__pb2.DeleteCollectionResponse.FromString,
                _registered_method=True)
        self.GetCollectionInfo = channel.unary_unary(
                '/vectordb.VectorDatabaseService/GetCollectionInfo',
                request_serializer=vectordb__pb2.GetCollectionInfoRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetCollectionInfoResponse.FromString,
                _registered_method=True)
        self.GetEmbeddingModels = channel.unary_unary(
                '/vectordb.VectorDatabaseService/GetEmbeddingModels',
                request_serializer=vectordb__pb2.GetEmbeddingModelsRequest.SerializeToString,
                response_deserializer=vectordb__pb2.GetEmbeddingModelsResponse.FromString,
                _registered_method=True)


class VectorDatabaseServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateCollection(self, request, context):
        """Create new collection and add all docuemnts in the request
        Documents do not necessarily match the required maximum size
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddDocuments(self, request, context):
        """Add documents to the existing collection
        Field `score` is ignored
        Documents do not necessarily match the required maximum size
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Search(self, request, context):
        """Search for relevant documents in the collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteCollection(self, request, context):
        """Delete an existing collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCollectionInfo(self, request, context):
        """Get information about an existing collection
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEmbeddingModels(self, request, context):
        """Get available embedding models
        Filter by language
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VectorDatabaseServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateCollection,
                    request_deserializer=vectordb__pb2.CreateCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.CreateCollectionResponse.SerializeToString,
            ),
            'AddDocuments': grpc.unary_unary_rpc_method_handler(
                    servicer.AddDocuments,
                    request_deserializer=vectordb__pb2.AddDocumentsRequest.FromString,
                    response_serializer=vectordb__pb2.AddDocumentsResponse.SerializeToString,
            ),
            'Search': grpc.unary_unary_rpc_method_handler(
                    servicer.Search,
                    request_deserializer=vectordb__pb2.SearchRequest.FromString,
                    response_serializer=vectordb__pb2.SearchResponse.SerializeToString,
            ),
            'DeleteCollection': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteCollection,
                    request_deserializer=vectordb__pb2.DeleteCollectionRequest.FromString,
                    response_serializer=vectordb__pb2.DeleteCollectionResponse.SerializeToString,
            ),
            'GetCollectionInfo': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCollectionInfo,
                    request_deserializer=vectordb__pb2.GetCollectionInfoRequest.FromString,
                    response_serializer=vectordb__pb2.GetCollectionInfoResponse.SerializeToString,
            ),
            'GetEmbeddingModels': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEmbeddingModels,
                    request_deserializer=vectordb__pb2.GetEmbeddingModelsRequest.FromString,
                    response_serializer=vectordb__pb2.GetEmbeddingModelsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vectordb.VectorDatabaseService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('vectordb.VectorDatabaseService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class VectorDatabaseService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/CreateCollection',
            vectordb__pb2.CreateCollectionRequest.SerializeToString,
            vectordb__pb2.CreateCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddDocuments(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/AddDocuments',
            vectordb__pb2.AddDocumentsRequest.SerializeToString,
            vectordb__pb2.AddDocumentsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Search(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/Search',
            vectordb__pb2.SearchRequest.SerializeToString,
            vectordb__pb2.SearchResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteCollection(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/DeleteCollection',
            vectordb__pb2.DeleteCollectionRequest.SerializeToString,
            vectordb__pb2.DeleteCollectionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetCollectionInfo(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/GetCollectionInfo',
            vectordb__pb2.GetCollectionInfoRequest.SerializeToString,
            vectordb__pb2.GetCollectionInfoResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEmbeddingModels(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/vectordb.VectorDatabaseService/GetEmbeddingModels',
            vectordb__pb2.GetEmbeddingModelsRequest.SerializeToString,
            vectordb__pb2.GetEmbeddingModelsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
